### ISSUE TITLE
Upgrading java code using deprecated raml-java-parser  to webapi-parser

### ISSUE THREAD

**Issue by hellboy81** [raml-org/webapi-parser#47]
subj

**Comment by hellboy81** [comment]
At the moment we are trying to use [soapui-raml-plugin](https://github.com/SmartBear/soapui-raml-plugin) and getting exception:

```java
ERROR: java.lang.NoClassDefFoundError: org/raml/v2/api/model/v10/api/Api

   java.lang.NoClassDefFoundError: org/raml/v2/api/model/v10/api/Api

                at java.lang.Class.getDeclaredMethods0(Native Method)

                at java.lang.Class.privateGetDeclaredMethods(Unknown Source)

                at java.lang.Class.privateGetPublicMethods(Unknown Source)

                at java.lang.Class.getMethods(Unknown Source)

                at java.beans.Introspector.getPublicDeclaredMethods(Unknown Source)

                at java.beans.Introspector.getTargetMethodInfo(Unknown Source)

                at java.beans.Introspector.getBeanInfo(Unknown Source)

                at java.beans.Introspector.getBeanInfo(Unknown Source)

                at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3292)

                at java.security.AccessController.doPrivileged(Native Method)

                at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3290)

                at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3266)

                at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:254)

                at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:285)

                at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:257)

                at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:875)

                at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:87)

                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)

                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)

                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)

                at com.smartbear.soapui.raml.RamlUtils.createRamlImporter(RamlUtils.groovy:28)

                at com.smartbear.soapui.raml.actions.RamlImporterWorker.construct(RamlImporterWorker.java:45)

                at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:47)

                at com.eviware.soapui.support.swing.SwingWorker.run(SwingWorker.java:88)

   Caused by: java.lang.ClassNotFoundException: org.raml.v2.api.model.v10.api.Api

                at java.net.URLClassLoader.findClass(Unknown Source)

                at java.lang.ClassLoader.loadClass(Unknown Source)

                at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

                at java.lang.ClassLoader.loadClass(Unknown Source)

                at com.eviware.soapui.plugins.JarClassLoader.loadClass(JarClassLoader.java:72)

                ... 24 more
````

As I mentioned this problem should be or can be solved replacing deprecated `raml-java-parser` with `webapi-parser`.


Replacements for `RamlModelBuilder` and another class are needed

```java
Error:(23, 90) java: package org.raml.v2.api.model.v10.api does not exist
Error:(29, 37) java: package org.raml.v2.api.model.v10.datamodel does not exist
```

**Comment by jstoiko** [comment]
sorry but I think you are posting this issue in the wrong repo. you might want to file it on https://github.com/SmartBear/soapui-raml-plugin
